name: LoungeServeur
version: 1.0
main: com.twizzyx.lounge.Main
api-version: 1.20
author: TwiZzyx

commands:
  bypassbuild:
    description: Active ou désactive le bypass des protections.
    usage: /bypassbuild
    permission: op

  lobby:
    description: Téléporte au lobby principal
    usage: /lobby
